### PR TITLE
Designer launch post

### PR DESCRIPTION
**Pull request by davidbanham**

### CODE REVIEW

**Comment by davidbanham** [comment]
Can haz review?

**Comment by jacklynrose** [comment]
@davidbanham can we close this and you move it to the medium blog?

**Comment by davidbanham** [comment]
We can close it if you or anyone else says one of the following things:
1. "Dave! I have read your post and I think that it is perfect and it should go on the blog."
2. "Dave! This is total bullshit. There is no way this can ever be brought up to standard. Flick a match into it and walk away. Cry yourself to sleep tonight you sack of crap."

I think the more likely case is that you or someone else says:

"Dave! I have read your post and it is good. I think you should tweak these n things and then it will be excellent."

In that case, we leave the PR open until I fix those n things, then we close it and publish the post.

**Comment by jacklynrose** [comment]
It's beautiful, it's wonderful, you're a star. Now just post it to the Medium blog 😹

**Comment by davidbanham** [comment]
https://medium.com/@davidbanham/designer-9240da4b56a0#.ssk51smmg

**Pull request closed without merging**
